// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ_090052Um8hC3z1-ba33-9jXZsLPrR4',
    appId: '1:292696234329:web:3af93345f56eb3a7a51448',
    messagingSenderId: '292696234329',
    projectId: 'final-note-taker',
    authDomain: 'final-note-taker.firebaseapp.com',
    storageBucket: 'final-note-taker.firebasestorage.app',
    measurementId: 'G-168QB2BBW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkF6ZzMGo8kGJJ3mBjFqjtxxfd6QTvGXg',
    appId: '1:292696234329:android:706291d9087a2749a51448',
    messagingSenderId: '292696234329',
    projectId: 'final-note-taker',
    storageBucket: 'final-note-taker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTmxAISvIX5n1ypU0VY3NFYG_X1Humsc',
    appId: '1:292696234329:ios:e6898d7da89df68ca51448',
    messagingSenderId: '292696234329',
    projectId: 'final-note-taker',
    storageBucket: 'final-note-taker.firebasestorage.app',
    iosBundleId: 'com.example.wilsonNoteTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoTmxAISvIX5n1ypU0VY3NFYG_X1Humsc',
    appId: '1:292696234329:ios:e6898d7da89df68ca51448',
    messagingSenderId: '292696234329',
    projectId: 'final-note-taker',
    storageBucket: 'final-note-taker.firebasestorage.app',
    iosBundleId: 'com.example.wilsonNoteTaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ_090052Um8hC3z1-ba33-9jXZsLPrR4',
    appId: '1:292696234329:web:5a8c2214bed23ed0a51448',
    messagingSenderId: '292696234329',
    projectId: 'final-note-taker',
    authDomain: 'final-note-taker.firebaseapp.com',
    storageBucket: 'final-note-taker.firebasestorage.app',
    measurementId: 'G-2Z9FVFJ6NX',
  );
}
